### ISSUE TITLE
page_chunks.class column NOT NULL

### ISSUE THREAD

**Issue by Pyro-San** [pyrocms/pyrocms-ci#3444]
On a new install it appears that the class column in the page_chunks table is set to NOT NULL, causing issues when updating page chunks.

**Comment by RyanThompson** [comment]
What version are you referring to on this one? Page chunks was removed in 2 I believe.

**Comment by Pyro-San** [comment]
I installed 2.2 today and came across the issue.
The class field is added in this migration
https://github.com/pyrocms/pyrocms-ci/blob/2.2/develop/system/cms/migrations/093_Add_page_chunk_class.php

**Comment by RyanThompson** [comment]
https://github.com/pyrocms/pyrocms-ci/commit/8050edc3555da20a82079915fc4bae2d006cb0ce should do it.
